language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - APP_ENV=testing
  - CODECLIMATE_REPO_TOKEN=ead81c9999c167a9dae8cd7f6b72537bf51d8898b276e7edcc096af60ed083f0 ./vendor/bin/test-reporter

before_script: 
  - composer install
  - mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

addons:
  code_climate:
    repo_token: ead81c9999c167a9dae8cd7f6b72537bf51d8898b276e7edcc096af60ed083f0

notifications:
  email:
    - bina.coulibaly@gmail.com
